/**:
  ros__parameters:
    tag_size: 0.0499
    tag_family: 'tagStandard52h13'
    get_debug_image: true
    expected_tags: 
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
