image_width: 640
image_height: 480
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [502.61949,   0.     , 383.28791,
           0.     , 676.73523, 234.55441,
           0.     ,   0.     ,   1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.053888, -0.019036, -0.004237, 0.021393, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [473.22215,   0.     , 402.56025,   0.     ,
           0.     , 676.86788, 233.0357 ,   0.     ,
           0.     ,   0.     ,   1.     ,   0.     ]