image_width: 640
image_height: 480
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [372.49373,   0.     , 327.83597,
           0.     , 495.48521, 237.14727,
           0.     ,   0.     ,   1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [0.032882, -0.054270, 0.002716, 0.006406, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [369.63635,   0.     , 334.2695 ,   0.     ,
           0.     , 500.31009, 238.28143,   0.     ,
           0.     ,   0.     ,   1.     ,   0.     ]