image_width: 640
image_height: 480
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [447.89892,   0.     , 340.1866 ,
           0.     , 446.33485, 229.05296,
           0.     ,   0.     ,   1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [0.086709, -0.104361, -0.004063, 0.004440, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [455.2261 ,   0.     , 343.73268,   0.     ,
           0.     , 455.74973, 227.12068,   0.     ,
           0.     ,   0.     ,   1.     ,   0.     ]