image_width: 640
image_height: 480
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [407.08168,   0.     , 329.11698,
           0.     , 409.27014, 241.55354,
           0.     ,   0.     ,   1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [0.035023, -0.070331, 0.008055, -0.000850, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [405.34808,   0.     , 329.12701,   0.     ,
           0.     , 410.62053, 245.00627,   0.     ,
           0.     ,   0.     ,   1.     ,   0.     ]