global_ekf:
  ros__parameters:
    frequency: 30.0                   # Lower frequency for global corrections
    world_frame: map                  # Output map → odom
    odom_frame: odom
    base_link_frame: base_link
    map_frame: map
    two_d_mode: false
    sensor_timeout: 0.05
    publish_tf: true
    use_control: false

    # Local EKF's odometry (odom → base_link)
    odom0: /local_odom
    odom0_config: [true, true, true,   # Enable position (X,Y,Z)
                   true, true, true,   # Enable orientation (roll, pitch, yaw)
                   true, true, true,   # Enable linear velocity
                   true, true, true,   # Enable angular velocity
                   true, true, true]
    odom0_differential: true          # Treat as relative motion between updates
    odom0_queue_size: 3
    odom0_pose_rejection_threshold: 0.5
    odom0_twist_rejection_threshold: 0.4
    odom0_linear_acceleration_rejection_threshold: 0.2

    # Camera Pose (map frame)
    pose0: /robot/pose
    pose0_config: [true, true, true,   # Enable position (X,Y,Z)
                   false, false, false,# Disable orientation (high covariance)
                   false, false, false, 
                   false, false, false]
    pose0_differential: false          # Absolute pose in map frame
    pose0_queue_size: 1
    pose0_pose_rejection_threshold: 1.0
    pose0_twist_rejection_threshold: 0.5
    pose0_linear_acceleration_rejection_threshold: 0.2
    pose0_nodelay: true

local_ekf:
  ros__parameters:
    frequency: 40.0
    world_frame: odom                 # Output odom → base_link
    odom_frame: odom
    base_link_frame: base_link
    map_frame: map
    two_d_mode: false
    sensor_timeout: 0.03
    publish_tf: true
    use_control: false

    # IMU (base_link frame)
    imu0: /imu/data
    imu0_config: [false, false, false,  # Disable position
                  true,  true,  true,   # Enable orientation (roll, pitch, yaw)
                  false, false, false,  # Disable linear velocity
                  true,  true,  true,   # Enable angular velocity
                  true, true, false]  # Disable linear acceleration
    imu0_differential: false
    imu0_remove_gravitational_acceleration: false
    imu0_queue_size: 1
    imu0_pose_rejection_threshold: 0.5
    imu0_twist_rejection_threshold: 0.5
    imu0_linear_acceleration_rejection_threshold: 0.2 
    imu0_nodelay: true

    